apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-local-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s-local-app
  template:
    metadata:
      labels:
        app: go-k8s-local-app
    spec:
      containers:
        - name: go-kubernetes-k8s-container
          image: coolersai/go-kubernetes-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
