apiVersion: v1
kind: Service
metadata:
  name: go-k8s-local-service
spec:
  type: NodePort
  selector:
    app: go-k8s-local-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
